bookmarks:
  # GitHub repos
  - title: "SSK-TBD/bluage"
    url: "https://github.com/SSK-TBD/bluage"
  - title: "SSK-TBD/canary-cloud-kanri"
    url: "https://github.com/SSK-TBD/canary-cloud-kanri"
  - title: "SSK-TBD/server"
    url: "https://github.com/SSK-TBD/server"
  - title: "SSK-TBD/platform-gha"
    url: "https://github.com/SSK-TBD/platform-gha"
  - title: "SSK-TBD/ops"
    url: "https://github.com/SSK-TBD/ops"
  - title: "SSK-TBD/manifests"
    url: "https://github.com/SSK-TBD/manifests"
  - title: "SSK-TBD/canary-web"
    url: "https://github.com/SSK-TBD/canary-web"
  - title: "SSK-TBD/canary-cloud-conv"
    url: "https://github.com/SSK-TBD/canary-cloud-conv"
  - title: "SSK-TBD/canary-react-native"
    url: "https://github.com/SSK-TBD/canary-react-native"
  - title: "SSK-TBD/tech-blog-review"
    url: "https://github.com/SSK-TBD/tech-blog-review"

  # GCP
  - title: "Home canary cloud dev"
    url: "https://console.cloud.google.com/home/dashboard?project=canary-cloud-dev"
  - title: "Home canary cloud stg"
    url: "https://console.cloud.google.com/home/dashboard?project=canary-cloud-stg"
  - title: "Home canary cloud prod"
    url: "https://console.cloud.google.com/home/dashboard?project=canary-cloud-prod"
  - title: "Home canary dev"
    url: "https://console.cloud.google.com/home/dashboard?project=canary-dev"
  - title: "Home canary stg"
    url: "https://console.cloud.google.com/home/dashboard?project=canary-stg"
  - title: "Home canary prod"
    url: "https://console.cloud.google.com/home/dashboard?project=canary-prod"
  - title: "Artifact Registry canary cloud dev"
    url: "https://console.cloud.google.com/artifacts?project=canary-cloud-dev"
  - title: "Artifact Registry canary cloud stg"
    url: "https://console.cloud.google.com/artifacts?project=canary-cloud-stg"
  - title: "Artifact Registry canary cloud prod"
    url: "https://console.cloud.google.com/artifacts?project=canary-cloud-prod"
  - title: "Artifact Registry canary dev"
    url: "https://console.cloud.google.com/artifacts?project=canary-dev"
  - title: "Artifact Registry canary stg"
    url: "https://console.cloud.google.com/artifacts?project=canary-stg"
  - title: "Artifact Registry canary prod"
    url: "https://console.cloud.google.com/artifacts?project=canary-prod"
  - title: "Cloud Storage canary cloud dev"
    url: "https://console.cloud.google.com/storage/browser?project=canary-cloud-dev"
  - title: "Cloud Storage canary cloud stg"
    url: "https://console.cloud.google.com/storage/browser?project=canary-cloud-stg"
  - title: "Cloud Storage canary cloud prod"
    url: "https://console.cloud.google.com/storage/browser?project=canary-cloud-prod"
  - title: "Cloud Storage canary dev"
    url: "https://console.cloud.google.com/storage/browser?project=canary-dev"
  - title: "Cloud Storage canary stg"
    url: "https://console.cloud.google.com/storage/browser?project=canary-stg"
  - title: "Cloud Storage canary prod"
    url: "https://console.cloud.google.com/storage/browser?project=canary-prod"
  - title: "BigQuery canary cloud dev"
    url: "https://console.cloud.google.com/bigquery?project=canary-cloud-dev"
  - title: "BigQuery canary cloud stg"
    url: "https://console.cloud.google.com/bigquery?project=canary-cloud-stg"
  - title: "BigQuery canary cloud prod"
    url: "https://console.cloud.google.com/bigquery?project=canary-cloud-prod"
  - title: "BigQuery canary dev"
    url: "https://console.cloud.google.com/bigquery?project=canary-dev"
  - title: "BigQuery canary stg"
    url: "https://console.cloud.google.com/bigquery?project=canary-stg"
  - title: "BigQuery canary prod"
    url: "https://console.cloud.google.com/bigquery?project=canary-prod"
  - title: "Cloud Scheduler canary cloud dev"
    url: "https://console.cloud.google.com/cloudscheduler?project=canary-cloud-dev"
  - title: "Cloud Scheduler canary cloud stg"
    url: "https://console.cloud.google.com/cloudscheduler?project=canary-cloud-stg"
  - title: "Cloud Scheduler canary cloud prod"
    url: "https://console.cloud.google.com/cloudscheduler?project=canary-cloud-prod"
  - title: "Cloud Scheduler canary dev"
    url: "https://console.cloud.google.com/cloudscheduler?project=canary-dev"
  - title: "Cloud Scheduler canary stg"
    url: "https://console.cloud.google.com/cloudscheduler?project=canary-stg"
  - title: "Cloud Scheduler canary prod"
    url: "https://console.cloud.google.com/cloudscheduler?project=canary-prod"
  - title: "PubSub - topic canary cloud dev"
    url: "https://console.cloud.google.com/cloudpubsub/topic/list?project=canary-cloud-dev"
  - title: "PubSub - topic canary cloud stg"
    url: "https://console.cloud.google.com/cloudpubsub/topic/list?project=canary-cloud-stg"
  - title: "PubSub - topic canary cloud prod"
    url: "https://console.cloud.google.com/cloudpubsub/topic/list?project=canary-cloud-prod"
  - title: "PubSub - topic canary dev"
    url: "https://console.cloud.google.com/cloudpubsub/topic/list?project=canary-dev"
  - title: "PubSub - topic canary stg"
    url: "https://console.cloud.google.com/cloudpubsub/topic/list?project=canary-stg"
  - title: "PubSub - topic canary prod"
    url: "https://console.cloud.google.com/cloudpubsub/topic/list?project=canary-prod"
  - title: "PubSub - subscription canary cloud dev"
    url: "https://console.cloud.google.com/cloudpubsub/subscription/list?project=canary-cloud-dev"
  - title: "PubSub - subscription canary cloud stg"
    url: "https://console.cloud.google.com/cloudpubsub/subscription/list?project=canary-cloud-stg"
  - title: "PubSub - subscription canary cloud prod"
    url: "https://console.cloud.google.com/cloudpubsub/subscription/list?project=canary-cloud-prod"
  - title: "PubSub - subscription canary dev"
    url: "https://console.cloud.google.com/cloudpubsub/subscription/list?project=canary-dev"
  - title: "PubSub - subscription canary stg"
    url: "https://console.cloud.google.com/cloudpubsub/subscription/list?project=canary-stg"
  - title: "PubSub - subscription canary prod"
    url: "https://console.cloud.google.com/cloudpubsub/subscription/list?project=canary-prod"
  - title: "Dataflow canary cloud dev"
    url: "https://console.cloud.google.com/dataflow/jobs?project=canary-cloud-dev"
  - title: "Dataflow canary cloud stg"
    url: "https://console.cloud.google.com/dataflow/jobs?project=canary-cloud-stg"
  - title: "Dataflow canary cloud prod"
    url: "https://console.cloud.google.com/dataflow/jobs?project=canary-cloud-prod"
  - title: "Dataflow canary dev"
    url: "https://console.cloud.google.com/dataflow/jobs?project=canary-dev"
  - title: "Dataflow canary stg"
    url: "https://console.cloud.google.com/dataflow/jobs?project=canary-stg"
  - title: "Dataflow canary prod"
    url: "https://console.cloud.google.com/dataflow/jobs?project=canary-prod"
  - title: "Cloud Build canary cloud dev"
    url: "https://console.cloud.google.com/cloud-build/builds?project=canary-cloud-dev"
  - title: "Cloud Build canary cloud stg"
    url: "https://console.cloud.google.com/cloud-build/builds?project=canary-cloud-stg"
  - title: "Cloud Build canary cloud prod"
    url: "https://console.cloud.google.com/cloud-build/builds?project=canary-cloud-prod"
  - title: "Cloud Build canary dev"
    url: "https://console.cloud.google.com/cloud-build/builds?project=canary-dev"
  - title: "Cloud Build canary stg"
    url: "https://console.cloud.google.com/cloud-build/builds?project=canary-stg"
  - title: "Cloud Build canary prod"
    url: "https://console.cloud.google.com/cloud-build/builds?project=canary-prod"
  - title: "Cloud Tasks canary cloud dev"
    url: "https://console.cloud.google.com/cloudtasks?project=canary-cloud-dev"
  - title: "Cloud Tasks canary cloud stg"
    url: "https://console.cloud.google.com/cloudtasks?project=canary-cloud-stg"
  - title: "Cloud Tasks canary cloud prod"
    url: "https://console.cloud.google.com/cloudtasks?project=canary-cloud-prod"
  - title: "Cloud Tasks canary dev"
    url: "https://console.cloud.google.com/cloudtasks?project=canary-dev"
  - title: "Cloud Tasks canary stg"
    url: "https://console.cloud.google.com/cloudtasks?project=canary-stg"
  - title: "Cloud Tasks canary prod"
    url: "https://console.cloud.google.com/cloudtasks?project=canary-prod"
  - title: "IAM canary cloud dev"
    url: "https://console.cloud.google.com/iam-admin/iam?project=canary-cloud-dev"
  - title: "IAM canary cloud stg"
    url: "https://console.cloud.google.com/iam-admin/iam?project=canary-cloud-stg"
  - title: "IAM canary cloud prod"
    url: "https://console.cloud.google.com/iam-admin/iam?project=canary-cloud-prod"
  - title: "IAM canary dev"
    url: "https://console.cloud.google.com/iam-admin/iam?project=canary-dev"
  - title: "IAM canary stg"
    url: "https://console.cloud.google.com/iam-admin/iam?project=canary-stg"
  - title: "IAM canary prod"
    url: "https://console.cloud.google.com/iam-admin/iam?project=canary-prod"
  - title: "Secret Manager canary cloud dev"
    url: "https://console.cloud.google.com/security/secret-manager?referrer=search&project=canary-cloud-dev"
  - title: "Secret Manager canary cloud stg"
    url: "https://console.cloud.google.com/security/secret-manager?referrer=search&project=canary-cloud-stg"
  - title: "Secret Manager canary cloud prod"
    url: "https://console.cloud.google.com/security/secret-manager?referrer=search&project=canary-cloud-prod"
  - title: "Secret Manager canary dev"
    url: "https://console.cloud.google.com/security/secret-manager?referrer=search&project=canary-dev"
  - title: "Secret Manager canary stg"
    url: "https://console.cloud.google.com/security/secret-manager?referrer=search&project=canary-stg"
  - title: "Secret Manager canary prod"
    url: "https://console.cloud.google.com/security/secret-manager?referrer=search&project=canary-prod"
  - title: "Compute Engine canary cloud dev"
    url: "https://console.cloud.google.com/compute/instances?project=canary-cloud-dev"
  - title: "Compute Engine canary cloud stg"
    url: "https://console.cloud.google.com/compute/instances?project=canary-cloud-stg"
  - title: "Compute Engine canary cloud prod"
    url: "https://console.cloud.google.com/compute/instances?project=canary-cloud-prod"
  - title: "Compute Engine canary dev"
    url: "https://console.cloud.google.com/compute/instances?project=canary-dev"
  - title: "Compute Engine canary stg"
    url: "https://console.cloud.google.com/compute/instances?project=canary-stg"
  - title: "Compute Engine canary prod"
    url: "https://console.cloud.google.com/compute/instances?project=canary-prod"
  - title: "Logging canary cloud dev"
    url: "https://console.cloud.google.com/logs/query?project=canary-cloud-dev"
  - title: "Logging canary cloud stg"
    url: "https://console.cloud.google.com/logs/query?project=canary-cloud-stg"
  - title: "Logging canary cloud prod"
    url: "https://console.cloud.google.com/logs/query?project=canary-cloud-prod"
  - title: "Logging canary dev"
    url: "https://console.cloud.google.com/logs/query?project=canary-dev"
  - title: "Logging canary stg"
    url: "https://console.cloud.google.com/logs/query?project=canary-stg"
  - title: "Logging canary prod"
    url: "https://console.cloud.google.com/logs/query?project=canary-prod"
  - title: "Monitoring canary cloud dev"
    url: "https://console.cloud.google.com/monitoring?referrer=search&project=canary-cloud-dev"
  - title: "Monitoring canary cloud stg"
    url: "https://console.cloud.google.com/monitoring?referrer=search&project=canary-cloud-stg"
  - title: "Monitoring canary cloud prod"
    url: "https://console.cloud.google.com/monitoring?referrer=search&project=canary-cloud-prod"
  - title: "Monitoring canary dev"
    url: "https://console.cloud.google.com/monitoring?referrer=search&project=canary-dev"
  - title: "Monitoring canary stg"
    url: "https://console.cloud.google.com/monitoring?referrer=search&project=canary-stg"
  - title: "Monitoring canary prod"
    url: "https://console.cloud.google.com/monitoring?referrer=search&project=canary-prod"
  - title: "Workflows canary cloud dev"
    url: "https://console.cloud.google.com/workflows?project=canary-cloud-dev"
  - title: "Workflows canary cloud stg"
    url: "https://console.cloud.google.com/workflows?project=canary-cloud-stg"
  - title: "Workflows canary cloud prod"
    url: "https://console.cloud.google.com/workflows?project=canary-cloud-prod"
  - title: "Workflows canary dev"
    url: "https://console.cloud.google.com/workflows?project=canary-dev"
  - title: "Workflows canary stg"
    url: "https://console.cloud.google.com/workflows?project=canary-stg"
  - title: "Workflows canary prod"
    url: "https://console.cloud.google.com/workflows?project=canary-prod"
  - title: "Cloud SQL canary cloud dev"
    url: "https://console.cloud.google.com/sql/instances/canary-cloud-dev/overview?project=canary-cloud-dev"
  - title: "Cloud SQL canary cloud stg"
    url: "https://console.cloud.google.com/sql/instances/canary-cloud-stg/overview?project=canary-cloud-stg"
  - title: "Cloud SQL canary cloud prod"
    url: "https://console.cloud.google.com/sql/instances/canary-cloud-prod/overview?project=canary-cloud-prod"
  - title: "Cloud SQL canary dev"
    url: "https://console.cloud.google.com/sql/instances/canary-dev/overview?project=canary-dev"
  - title: "Cloud SQL canary stg"
    url: "https://console.cloud.google.com/sql/instances/canary-stg/overview?project=canary-stg"
  - title: "Cloud SQL canary prod"
    url: "https://console.cloud.google.com/sql/instances/canary-prod/overview?project=canary-prod"

  # spanner
  - title: "Spanner bluage-spanner"
    url: "https://console.cloud.google.com/spanner/instances?referrer=search&hl=ja&inv=1&invt=AbpSfQ&project=bluage-spanner"
  - title: "Spanner bluage-spanner bluage-shared"
    url: "https://console.cloud.google.com/spanner/instances/bluage-shared/details/databases?hl=ja&inv=1&invt=AbpSfQ&project=bluage-spanner"
  - title: "Spanner bluage-spanner bluage-shared canary-cloud-dev"
    url: "https://console.cloud.google.com/spanner/instances/bluage-shared/databases/canary-cloud-dev/details/query?hl=ja&inv=1&invt=AbpSfQ&project=bluage-spanner"
  - title: "Spanner bluage-spanner bluage-shared canary-cloud-stg"
    url: "https://console.cloud.google.com/spanner/instances/bluage-shared/databases/canary-cloud-stg/details/query?hl=ja&inv=1&invt=AbpSfQ&project=bluage-spanner"
  - title: "Spanner bluage-spanner bluage-shared canary-cloud-prod"
    url: "https://console.cloud.google.com/spanner/instances/bluage-shared/databases/canary-cloud-prod/details/query?hl=ja&inv=1&invt=AbpSfQ&project=bluage-spanner"
  - title: "Spanner bluage-spanner bluage-shared canary-prod"
    url: "https://console.cloud.google.com/spanner/instances/bluage-shared/databases/canary-prod/details/query?hl=ja&inv=1&invt=AbpSfQ&project=bluage-spanner"

  # GKE
  - title: "GKE workload prod"
    url: "https://console.cloud.google.com/kubernetes/workload/overview?hl=ja&inv=1&invt=AbpVfg&project=canary-prod"
  - title: "GKE workload stg"
    url: "https://console.cloud.google.com/kubernetes/workload/overview?hl=ja&inv=1&invt=AbpVfg&project=canary-stg"
  - title: "GKE workload dev"
    url: "https://console.cloud.google.com/kubernetes/workload/overview?hl=ja&inv=1&invt=AbpVfg&project=canary-dev-214513"

  # Datadog
  - title: "Datadog Home"
    url: "https://app.datadoghq.com/apm/home?env=prod"
  - title: "Datadog canary cloud prod"
    url: "https://app.datadoghq.com/apm/entity/service%3Acanary-cloud-prod?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%210%29&env=prod&fromUser=false&groupMapByOperation=null&operationName=opencensus&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%211%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cchanges%3A%28%29%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3AserviceAndInferred%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&start=1739325104274&end=1739328704274&paused=false"
